# ============================================================================
#  Builds a single-file TCG_Addressables_Patcher.exe
#  Embeds the .ps1 (optional logo file if present), extracts to temp, runs PowerShell.
#
#  Run:
#    powershell -ExecutionPolicy Bypass -File .\build_patcher_exe.ps1
# ============================================================================
$ErrorActionPreference = 'Stop'
$Root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }

$ps1Path   = Join-Path $Root 'TCG_Addressables_Patcher.ps1'
$asciiPath = Join-Path $Root 'ascii-rainzy.txt'
$outExe    = Join-Path $Root 'TCG_Addressables_Patcher.exe'
$genCs     = Join-Path $Root 'TCG_Addressables_Patcher_Launcher.g.cs'
$csc       = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'

if (-not (Test-Path -LiteralPath $ps1Path)) { throw "Missing: $ps1Path" }
if (-not (Test-Path -LiteralPath $csc))     { throw "Missing csc.exe: $csc" }

function Get-Base64File([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { return '' }
    return [Convert]::ToBase64String([IO.File]::ReadAllBytes($Path))
}

$ps1B64   = Get-Base64File $ps1Path
$asciiB64 = Get-Base64File $asciiPath

# Build C# with StringBuilder so huge base64 never breaks quoting
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// AUTO-GENERATED by build_patcher_exe.ps1 - do not edit by hand')
[void]$sb.AppendLine('// Single-file launcher for TCG Addressables Patcher (by Rain)')
[void]$sb.AppendLine('using System;')
[void]$sb.AppendLine('using System.Diagnostics;')
[void]$sb.AppendLine('using System.IO;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('internal static class Program')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private const string Ps1B64 =')
[void]$sb.AppendLine('        "' + $ps1B64 + '";')
[void]$sb.AppendLine('    private const string AsciiB64 =')
[void]$sb.AppendLine('        "' + $asciiB64 + '";')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    private static int Main()')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        Console.Title = "TCG Addressables Patcher - by Rain";')
[void]$sb.AppendLine('        string work = Path.Combine(')
[void]$sb.AppendLine('            Path.GetTempPath(),')
[void]$sb.AppendLine('            "TCG_AddrPatch_" + Process.GetCurrentProcess().Id.ToString());')
[void]$sb.AppendLine('        try')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            Directory.CreateDirectory(work);')
[void]$sb.AppendLine('            string ps1 = Path.Combine(work, "TCG_Addressables_Patcher.ps1");')
[void]$sb.AppendLine('            string ascii = Path.Combine(work, "ascii-rainzy.txt");')
[void]$sb.AppendLine('            File.WriteAllBytes(ps1, Convert.FromBase64String(Ps1B64));')
[void]$sb.AppendLine('            if (!string.IsNullOrEmpty(AsciiB64))')
[void]$sb.AppendLine('            {')
[void]$sb.AppendLine('                byte[] asciiBytes = Convert.FromBase64String(AsciiB64);')
[void]$sb.AppendLine('                if (asciiBytes != null && asciiBytes.Length > 0)')
[void]$sb.AppendLine('                    File.WriteAllBytes(ascii, asciiBytes);')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine('            string shell = ResolvePowerShell();')
[void]$sb.AppendLine('            // Persist backups / marker next to the .exe, not in %TEMP%')
[void]$sb.AppendLine('            string exeDir = AppDomain.CurrentDomain.BaseDirectory;')
[void]$sb.AppendLine('            if (!string.IsNullOrEmpty(exeDir))')
[void]$sb.AppendLine('                Environment.SetEnvironmentVariable("TCG_ADDR_PATCHER_ROOT", exeDir.TrimEnd(''\\'', ''/''));')
[void]$sb.AppendLine('            ProcessStartInfo psi = new ProcessStartInfo();')
[void]$sb.AppendLine('            psi.FileName = shell;')
[void]$sb.AppendLine('            psi.Arguments = string.Format("-NoProfile -ExecutionPolicy Bypass -File \"{0}\"", ps1);')
[void]$sb.AppendLine('            psi.UseShellExecute = false;')
[void]$sb.AppendLine('            psi.WorkingDirectory = work;')
[void]$sb.AppendLine('            using (Process p = Process.Start(psi))')
[void]$sb.AppendLine('            {')
[void]$sb.AppendLine('                if (p == null)')
[void]$sb.AppendLine('                {')
[void]$sb.AppendLine('                    Console.Error.WriteLine("Failed to start PowerShell.");')
[void]$sb.AppendLine('                    return 1;')
[void]$sb.AppendLine('                }')
[void]$sb.AppendLine('                p.WaitForExit();')
[void]$sb.AppendLine('                return p.ExitCode;')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('        catch (Exception ex)')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            Console.ForegroundColor = ConsoleColor.Red;')
[void]$sb.AppendLine('            Console.Error.WriteLine("[FAIL] " + ex.Message);')
[void]$sb.AppendLine('            Console.ResetColor();')
[void]$sb.AppendLine('            Console.WriteLine("Press Enter to close...");')
[void]$sb.AppendLine('            try { Console.ReadLine(); } catch { }')
[void]$sb.AppendLine('            return 1;')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('        finally')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            try')
[void]$sb.AppendLine('            {')
[void]$sb.AppendLine('                if (Directory.Exists(work))')
[void]$sb.AppendLine('                    Directory.Delete(work, true);')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine('            catch { }')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    private static string ResolvePowerShell()')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        try')
[void]$sb.AppendLine('        {')
[void]$sb.AppendLine('            string pathEnv = Environment.GetEnvironmentVariable("PATH") ?? "";')
[void]$sb.AppendLine('            foreach (string dir in pathEnv.Split('';''))')
[void]$sb.AppendLine('            {')
[void]$sb.AppendLine('                if (string.IsNullOrWhiteSpace(dir)) continue;')
[void]$sb.AppendLine('                string cand = Path.Combine(dir.Trim(), "pwsh.exe");')
[void]$sb.AppendLine('                if (File.Exists(cand)) return cand;')
[void]$sb.AppendLine('            }')
[void]$sb.AppendLine('        }')
[void]$sb.AppendLine('        catch { }')
[void]$sb.AppendLine('        string winPs = Path.Combine(Environment.SystemDirectory, "WindowsPowerShell", "v1.0", "powershell.exe");')
[void]$sb.AppendLine('        if (File.Exists(winPs)) return winPs;')
[void]$sb.AppendLine('        return "powershell.exe";')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('}')

$csText = $sb.ToString()
[IO.File]::WriteAllText($genCs, $csText, [Text.UTF8Encoding]::new($false))
Write-Host "Generated: $genCs"

& $csc /nologo /optimize+ /target:exe /out:"$outExe" /platform:anycpu "$genCs"
if ($LASTEXITCODE -ne 0) { throw "csc failed with exit $LASTEXITCODE" }

$info = Get-Item -LiteralPath $outExe
Write-Host ''
Write-Host "OK  Built single-file EXE:" -ForegroundColor Green
Write-Host "    $($info.FullName)"
Write-Host "    Size: $([math]::Round($info.Length / 1KB, 1)) KB"
Write-Host ''
Write-Host 'Share just that .exe - no .ps1 / .bat needed.'
Write-Host 'Double-click or run from a terminal.'
Write-Host 'Requires Windows PowerShell (built into Windows) or pwsh.'
